### ISSUE TITLE
Corpy with UDPipe2

### ISSUE THREAD

**Issue by RasmusBacklund** [dlukes/corpy#20]
Hi!

Is it possible to use corpy with UDPipe2? If so, what file should I give as parameter to corpy.udpipe.Model()?

**Comment by dlukes** [comment]
Unfortunately no :( UDPipe 2 is architecturally very different from UDPipe 1, Corpy just wraps UDPipe 1's relatively straightforward (if somewhat low-level, hence the wrapper) API, whereas UDPipe 2 is more of a research project with complicated dependencies and runtime constraints.

When [LinPipe](https://github.com/ufal/linpipe) comes out though, which is meant to incorporate work on what would have been UDPipe 3 and MorphoDiTa 2 AFAIK, and which should be again architecturally similar to UDPipe 1 and MorphoDiTa 1, I'd like to add support for that, as long as LinPipe offers a package on PyPI similar to what UDPipe 1 and MorphoDiTa 1 offer.

Does that make sense? Please re-open if no :)
